version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    links:
      - mysql:db

volumes:
  mysql_data:
    driver: local
